import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import PostHogPageView from './providers/PostHogPageView';
import { PHProvider } from './providers/PHProvider';
import { Suspense } from 'react';
import { LoadingSkeleton } from './components/LoadingSkeleton';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <PHProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Suspense fallback={<LoadingSkeleton />}>
            <PostHogPageView />
            {children}
          </Suspense>
        </body>
      </PHProvider>
    </html>
  );
}
